apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-ui
spec:
  selector:
    matchLabels:
      app: network-ui
  template:
    metadata:
      labels:
        app: network-ui
    spec:
      containers:
        - name: network-ui
          image: gcr.io/pure-phalanx-344719/network-ui
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_DEFAULT_API
              value: "https://api.web10.network"
            - name: PORT
              value: "80"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits: