apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-api
spec:
  selector:
    matchLabels:
      app: network-api
  template:
    metadata:
      labels:
        app: network-api
    spec:
      containers:
        - name: network-api
          image: gcr.io/pure-phalanx-344719/network-api
          ports:
            - containerPort: 80
          env:
            - name: STRIPE_STATUS
              value: "live"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits: