apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: web10
build:
  artifacts:
    - image: gcr.io/pure-phalanx-344719/network-api
      context: ../../api
    - image: gcr.io/pure-phalanx-344719/network-ui
      context: ../../ui
deploy:
  kubectl:
    manifests:
      - kuberapi.yml
      - kuberui.yml