version: "3"

services:
  api:
    build: api
    volumes:
      - ./api/:/api 
    ports:
      - "6000:80"
    environment:
      VIRTUAL_HOST: api.localhost
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
    networks:
      default:
        aliases:
          - api.localhost
  # auth:
  #   build: auth
  #   volumes:
  #     - ./auth:/frontend
  #     - node-modules:/frontend/node_modules
  #   command: ["npm", "run", "start"]
  #   environment:
  #     PORT: 80
  #     VIRTUAL_HOST: auth.localhost
  #     CHOKIDAR_USEPOLLING: "true"
  #   ports:
  #     - '3000:80'
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

volumes:
  network-ui-node-modules: