version: "3"

services:
  api:
    build: api
    volumes:
      - ./api/:/api 
    ports:
      - "6000:80"
    environment:
      VIRTUAL_HOST: api.localhost
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
    networks:
      default:
        aliases:
          - api.localhost
  ui:
    build:
      context: ./ui
      target: ui-dev
    volumes:
      - ./ui:/ui
      - ui-node-modules:/ui/node_modules
    command: ["npm", "run", "start"]
    environment:
      NODE_ENV: development
      PORT: 80
      VIRTUAL_HOST: ui.localhost
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    ports:
      - '3000:80'
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

volumes:
  ui-node-modules: